import{i as c}from"./assets/vendor-iVKk4foX.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const l="https://683d54c2199a0039e9e4fc76.mockapi.io/",d=()=>fetch(`${l}/posts`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()}),p=t=>{const e={method:"POST",body:JSON.stringify(t),headers:{"Content-Type":"application/json"}};return fetch(`${l}/posts`,e).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})},f=t=>{const e={method:"DELETE"};return fetch(`${l}/posts/${t}`,e).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})},m=({id:t,title:e,body:o})=>`
<li class="posts-list-item">
  <button class="post-delete-btn" type="button" data-delete data-post-id='${t}' >
    <svg class="post-delete-icon" width="16" height="16">
       <use href="../img/icons.svg#icon-trash"></use>
      </svg>
   </button>
   <h3 class="posts-list-item-title">${e}</h3>
  <p class="posts-list-item-text">${o}</p>
</li>

  `;console.log(f);const a={postList:document.querySelector(".js-posts-list"),postForm:document.querySelector(".js-post-form")},u=()=>{d().then(t=>{const e=t.map(o=>m(o)).join(" ");a.postList.innerHTML=e}).catch(t=>{console.log(t)})};u();const h=t=>{t.preventDefault();const{currentTarget:e}=t;console.dir(e);const o={title:e.elements.post_title.value.trim(),body:e.elements.post_body.value.trim()};if(Object.values(o).find(s=>s==="")===""){c.warning({title:"Warning",message:"All fields must be filled out",timeout:3e3,position:"topRight",messageColor:"#fff",titleColor:"#fff",backgroundColor:"#FFA500"});return}p(o).then(s=>{c.success({title:"Success",message:`${s.title} added successfully!`,timeout:3e3,position:"topRight",messageColor:"#fff",titleColor:"#fff"}),e.reset(),u(),console.log(s)}).catch(s=>{console.log(s)})},g=t=>{const e=t.target.closest("button[data-delete]");if(e===null)return;const o=e.dataset.postId;f(o).then(n=>{c.success({title:"Success",message:`${n.title} successfully deleted!`,timeout:3e3,position:"topRight"}),u()}).catch(n=>{console.log(n)})};a.postForm.addEventListener("submit",h);a.postList.addEventListener("click",g);
//# sourceMappingURL=index.js.map
